### ISSUE TITLE
Migrate content: articles

### ISSUE THREAD

**Issue by cbrody** [IIED-org/pubs#119]
Articles are still being edited on the current D7 site but the Article field map is more or less complete.

**Comment by finnlewis** [comment]
I have the article content type  mostly working, on https://github.com/IIED-org/pubs/tree/feature/119-migrate-content-articles

**Comment by finnlewis** [comment]
The artilces migration is merged indev-master and ready for test.

**Comment by finnlewis** [comment]
Thanks @cbrody 

This should be fixed with https://github.com/IIED-org/pubs/pull/158

Sorry for missing these first time.

On the test node in question, on my local, I do now have the article type and project reference: 

![image](https://user-images.githubusercontent.com/326588/155370415-14999a3a-d5ef-452b-b677-a331e4703e36.png)

**Comment by cbrody** [comment]
This looks to be all in order now, closing.

**Comment by cbrody** [comment]
Hi @finnlewis it looks like the source field_contact_0 is not being mapped to field_contact on the target, so re-opening.

**Comment by finnlewis** [comment]
For example: 
https://www.iied.org/building-women-led-community-climate-movement
https://pubs-dev.ac.iied.org/building-women-led-community-climate-movement

**Comment by finnlewis** [comment]
Hey @cbrody 

This PR https://github.com/IIED-org/pubs/pull/319 should fix the contact mapping.

Note, on the node in question, there are two images in the contact field. One is OK, the other does not seem to be in the file managed table, so the rwrite rule does not work.

> Rewrite inline image styles: Cannot find reference to pictures/picture-6526-1550233050.jpg from node 28496.

**Comment by cbrody** [comment]
Needs manual fix, noted and closing.
