### ISSUE TITLE
Migrate content: paragraphs

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#122]
Hi @cbrody 

The project nodes have two paragraphs reference fields.

- field_full_width_media (4 paragraphs have a value for this feild)
- field_additional_elements (10 paragraphs have a value for this feild)

I am now looking at the paragraphs more closely and considering a full migration of all paragraph data. 

Before I do dive in, it seems wise to check to confirm we do want to bring all paragraph bundles and content over. 

So I guess my first questions is: 

Are there any paragraphs bundles we don't want to migrate? 

Here are the Drupal 7 paragraphs: 

- About the author (about_the_author) 
- Accordion (accordion) 
- Accordion Item (accordion_item)
- Basic text (basic_text) 
- Colorbox gallery (colorbox_gallery) 
- Colorbox gallery thumbnails (colorbox_gallery_thumbnails)
- Events news blogs (events_news_blogs) 
- Events news blogs articles (events_news_blogs_articles) 
- Events news blogs small (events_news_blogs_small) 
- File upload (file_upload) 
- Focus area (focus_area)
- Image (image)
- Image wide (image_wide)
- Info box (info_box)
- lr colorbox wide (lr_colorbox_wide) 
- Media embed (media_embed)
- Media list (media_object) 
- Related link (related_link)
- Research projects articles (research_projects_articles)
- Research projects articles small (research_projects_articles_small) 
- Researcher profiles (researcher_profiles) 
- Small continued (small_continued) 
- Timeline (timeline) 
- Top six (top_six)
- Video embed (video_embed)
- Video embed standard (video_embed_standard)

**Comment by finnlewis** [comment]
Thanks @ncktrnr on the call today for pointing me towards: https://docs.google.com/spreadsheets/d/1OuUOnnKoVaOM3e7TNmnXGeWk9JUL3cMFEk9V-wsrQe0/edit#gid=675884710

I've written the migrations for the paragraph fields that are needed for the project content type. 

I'll follow suit for the article content type, but acknowledge that some paragraph bundles are not used and others may be considered low value, so we can assess as we progress with the migrations to avoid wasting time writing migrations for paragraphs that are not used or not wanted.

**Comment by finnlewis** [comment]
This is also ready for testing on dev-master @cbrody 

It would be good to pick a few imoprtant paragraphs as indicators to test.

**Comment by cbrody** [comment]
@finnlewis we don't need the field_full_width_media now, can this be removed from the relevant migration(s) and config please? @ncktrnr could you assist with testing this migration please?

**Comment by finnlewis** [comment]
- [ ] remove the field_full_width_media field from the **project** content type and the **article** content type
- [ ] remove the migration of the field_full_width_media from **project** migration and **article** migration

**Comment by finnlewis** [comment]
Hi @cbrody and @ncktrnr 

This should be ready for review on https://github.com/IIED-org/pubs/issues/122

I also removed the migration: iied_d7_project_para_full_width_media, which only had 4 records.

**Comment by cbrody** [comment]
I'm not sure how best to test this migration – let's discuss @ncktrnr

**Comment by cbrody** [comment]
Several issues found, please see [Testing spreadsheet](https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=794422499) for details.

**Comment by finnlewis** [comment]
Hi @cbrody 

I've fixed the event multiple file upload migration issue where the uploads were not on the event. 

See pull request here: https://github.com/IIED-org/pubs/compare/dev-master...feature/122-remove-paragraphs?expand=1

**Comment by cbrody** [comment]
Pull request now merged, thanks @finnlewis !

**Comment by finnlewis** [comment]
### node/138216 - https://www.iied.org/does-global-biodiversity-framework-offer-plan-b-for-protected-areas

@cbrody another fix ready for review.

On the blog post "Does the global biodiversity framework offer a plan B for protected areas?" I've fixed the missing image paragraph fields for media item and image caption. I'd missed the fields in the mapping and in the database query.

Looking better now on the node edit form:


![image](https://user-images.githubusercontent.com/326588/175130939-cf5e1df7-2ee5-467e-8d51-162c665907dd.png)

This is row 9 on the [testing spreadsheet](https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=794422499): 

Pull request that fixes this here: https://github.com/IIED-org/pubs/pull/287

**Comment by finnlewis** [comment]
I note on the above paragraph, we might want to change the media widget and also restrict media items to single cardinality.

**Comment by cbrody** [comment]
Closing this as any outstanding issues are not related to migration.
