### ISSUE TITLE
Migrate content: blogs

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#124]

**Comment by finnlewis** [comment]
Notes to self: 

There are a number of paragraph types allowed on the Drupal 7 blog content type, including the video_embed paragraph.

It turns out that video_embed paragraph is not used on any live blog post, as far as I can tell.

```
SELECT *
FROM `field_data_field_video` fv
LEFT JOIN field_data_field_paragraphs fp on fp.field_paragraphs_value =  fv.entity_id
WHERE fv.entity_type = 'paragraphs_item' 
AND fp.bundle = 'blog'
ORDER BY fv.bundle DESC

No rows. 
```

but for one_page
```
SELECT *
FROM `field_data_field_video` fv
LEFT JOIN field_data_field_paragraphs fp on fp.field_paragraphs_value =  fv.entity_id
WHERE fv.entity_type = 'paragraphs_item' 
AND fp.bundle = 'one_page'
ORDER BY fv.bundle DESC

38 rows
```

event: 1 row (nid 25781)
article: 2 rows (nids: 27381 / 27381)
media_release: 0
press: 0

**Comment by finnlewis** [comment]
@cbrody I think the blogs migration branch is ready for testing: 
https://github.com/IIED-org/pubs/tree/feature/124-migrate-content-blogs 

As dependencies, we need to 

1. run the iied_d7_terms_person migration to get user pictures migrated to the person taxonomy (note - we will probably want to review what other data we want to migrate on this one)
2. run the iied_d7_field_about_the_author migration to get the about paragraphs across. 

This should work: 

```
lando drush mim iied_d7_terms_person
lando drush mim iied_d7_field_about_the_author
lando drush mim iied_d7_blogs
```
Looking at the resulting data, we do now have a user reference to the author / person taxonomy directly in the content type and also in the 'about the author' paragraph. This is perhaps duplication we can get rid of. 

Let me know what you think.

**Comment by cbrody** [comment]
Hi @finnlewis the Blogger info field seems to contain a copy of the body field instead of content from field_blogger_info

**Comment by cbrody** [comment]
@ncktrnr The target D9 date field only contains the start date as per Finn's question in cell O9 here - is that OK?
https://docs.google.com/spreadsheets/d/1OuUOnnKoVaOM3e7TNmnXGeWk9JUL3cMFEk9V-wsrQe0/edit#gid=386629104

**Comment by cbrody** [comment]
@ncktrnr can we discuss on Monday? Cheers.

**Comment by cbrody** [comment]
> The target D9 date field only contains the start date as per Finn's question in cell O9 here - is that OK? https://docs.google.com/spreadsheets/d/1OuUOnnKoVaOM3e7TNmnXGeWk9JUL3cMFEk9V-wsrQe0/edit#gid=386629104

Realised this relates to Events, not Blogs so closing this!
