### ISSUE TITLE
Migrate content: translations

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#132]
A few of hte projects on the Drupal 7 site have translations, so it is important that we do not lose these in the migration.

For example: 

 - https://www.iied.org/node/454
 - https://www.iied.org/gwi-west-africa-project-background
 - https://www.iied.org/fr/gwi-afrique-de-louest-contexte-du-projet

**Comment by cbrody** [comment]
We're now manually migrating other translated content so closing this out for now.
