### ISSUE TITLE
Migrate content: news/press

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#133]
Issue to track migration of news and press into a single news content type.

**Comment by cbrody** [comment]
This is ready to test on Acquia dev (https://pubs-dev.ac.iied.org) – @ncktrnr could you have a look at this for completeness if you get a chance ?

**Comment by cbrody** [comment]
We'll need a new select list `field_news_type` in the news content type (details in row 48 of the 
 [Content Modelling ](https://docs.google.com/spreadsheets/d/1OuUOnnKoVaOM3e7TNmnXGeWk9JUL3cMFEk9V-wsrQe0/edit#gid=2055354944) sheet. The migration should populate the field accordingly if the source content type is Press release. @finnlewis could you implement this please?

**Comment by finnlewis** [comment]
Discussed this today with @cbrody - we'll go with a new taxonomy for "News type" to include initial terms of: 

Press release
News
Reaction

"News" and "Press release" will be populated by default on migration from the former respective content types.

**Comment by finnlewis** [comment]
Hi @cbrody 

Just to confirm the mappings on this: 

news_media source content type will be typed as "News"
news_press source content type will be typed as "Press release"

I don't this we migrate any news that is classed as "Reaction"

Have I got that right?

Cheers,

Finn

**Comment by cbrody** [comment]
The migration looks good to go, thanks.
