### ISSUE TITLE
Migrate: redirects

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#138]
There are about 3500 redirects which might need to be migrated. 

Some redirects will be auto generated from node/{nid} to /human/readable/path

Others will be from updated alias to /old/path to /new/path

We might want to filter out some redirects. 

- [x] Assess scale of migrations
- [x] Assess any redirects we want to ignore
- [x] Avoid duplicates

**Comment by finnlewis** [comment]
Hi @cbrody 

Total redirects in the Drupal 7 redirects table: 3497

The patterns that reference Drupal internal paths are as follows:
 
- node/* (2665)
- file/* (292)
- taxonomy/term/* (276)
- user/* (156)
- blog/* (29)

This leaves about 80 redirects that are path to path redirects. A few of the remaining are to fully qualified domain paths like http://pubs.iied.org/briefings.php and http://www.iied.org/pubs/search.php

Primarily we need to consider how to deal with each of the Drupal entity types. 

## Nodes

For each redirect that points to node/* I'm checking the original content type and if it is one of the following types, we will have migrated the node so we look up the new node id in the appropriate migrate_map table: 

- 'article'
-  'blog'
- 'event'
- 'project'
- 'press'
- 'media_release' 

For example, /COP26pod originally redirects to node/138896, on my local migration now redirects to node/74616, which in both cases is the article at https://www.iied.org/walking-talk-climate-ambition-why-walk-needs-nature-too-make-change-happen-podcast-episode-14

All other node/* redirects are ignored. For example where the content type is 'book' or something else. 

- [ ] Question: Does this cover all the node/* redirect migrations we need?

## Files

I'm not sure if we want to migrate these redirects. For example: 
file/gustavo300jpg redirects to file/176316 which then takes us to the path alias version, so all these redirect to the same place: 
 
https://www.iied.org/file/gustavo300jpg
https://www.iied.org/file/176316
https://www.iied.org/file/picture-13111-1636100901jpg 

- [ ] Question: Do we want to migrate redirects to file/* paths?

## Taxonomy terms

For example 
https://www.iied.org/barbara-ward-2021 Forwards to taxonomy/term/2731 which is https://www.iied.org/barbara-ward-lectures

- [ ] Question: Do we want to migrate redirects to taxonomy/term/* paths?

## Users

https://www.iied.org/users/gabriela-flores redirects to user/2421 which has the path alias: https://www.iied.org/users/gabriela-flores-zavala

We have migrated users to the person / author taxonomy, so we could migrate these redirects to the new taxonomy terms. 

- [ ] Question: Do we want to migrate redirects to users/* paths?

## Blogs

blogs/sam-duby-jorund-buen goes to blog/1867 which takes us to https://www.iied.org/blogs/sam-duby 

- [ ] Question: Do we want to migrate redirects to blogs/* paths?

**Comment by cbrody** [comment]
I'm pretty sure the answers are as follows but could use another pair of eyes. @ncktrnr & @DavidIIED could you consider Finn's questions above please? 

Q1 (nodes): This probably covers all the node/* redirects we need.
Q2 (files): Probably don't need these.
Q3 (taxonomy/term): We probably want these, yes.
Q4 (users): Yes I think we need these.
Q5 (blogs): Don't think we need these.

**Comment by cbrody** [comment]
Hi @finnlewis we've discussed this and my answers above are correct. Re Users, the path aliases will be changed to /people/firstName-[middleInitial-]lastName. There may be some Pages that we need to manually recreate redirects for once they've been built (e.g. /ar2011). We will look at the [search404 project](https://www.drupal.org/project/search404) for redirecting to a SERP.

**Comment by finnlewis** [comment]
Hi @cbrody 

I've updated the redirects migration to bring over the redirects with user entity targets. 

You mention the path aliases will be changed to /people/firstName-[middleInitial-]lastName. 

There are already lots of taxonomy terms in the person taxonomy, with paths like: https://pubs.iied.org/author/abbi-buxton. The iied_d7_terms_person migration looks to migrate about 700 users into the person taxonomy, which has over 6000 terms. 

So we will want to update the path aliases for all 6000 terms and add redirects at that point from /author/abbi-buxton to /people/abbi-buxton (for example).

I wonder if this is best done with a hook_update_N function that we can test and then run once on deployment. Or this might actually be covered with 'bulk update' of url aliases at admin/config/search/path/update_bulk.

**Comment by cbrody** [comment]
Hi @finnlewis yes I think the 'bulk update' feature should suffice for updating the existing terms. We'll need to change to vocabulary name from 'Author' to 'People' prior to running the migration.

**Comment by finnlewis** [comment]
Passing this to @cbrody for testing.

**Comment by finnlewis** [comment]
Hi @cbrody 

As noted on #145 the migration of user path aliases to new redirects was a separate job. 

The iied_d7_redirects migration only deals with existing redirects, some of which are to users. 

I think this is all working as expected now and ready to test. 

Many thanks,

Finn

**Comment by cbrody** [comment]
I've renamed the Author vocab to People, closing this issue.

**Comment by cbrody** [comment]
@finnlewis re-opening this as the path aliases for the Collection vocabulary have been changed to from /[term:name] to /collection/[term:name] so we'll need redirects for these - is this straightforward to add to the migration? If not we can add them manually.

**Comment by finnlewis** [comment]
I've addressed the first issue with the merge request https://github.com/IIED-org/pubs/pull/323/files

**Comment by finnlewis** [comment]
Just added a commit that addresses the second part: 

![image](https://user-images.githubusercontent.com/326588/180256483-11d1767b-6d41-4527-a5f7-0daecad91f96.png)
