### ISSUE TITLE
Migration: user aliases to redirects

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#145]
The old user/uid path aliases are like https://www.iied.org/users/gabriela-flores-zavala

The new user taxonomy paths are like https://pubs.iied.org/author/anna-schulz

We will need to migrate the old user aliases to the new taxonomy term Drupal paths as new redirects.

So we'll add ar redirect something like: 

/users/gabriela-flores-zavala -> taxonom/tem/[TID]

**Comment by finnlewis** [comment]
Hi @cbrody 

So sorry, I failed to notice I needed to write a new migration for user paths.

This is done now, please see corresponding pull request.

Once migrated, we do have the expected redirects in place: 

![image](https://user-images.githubusercontent.com/326588/153262776-03baa1fb-efa8-40d2-ba83-eefbd3674228.png)

**Comment by cbrody** [comment]
Reopening in light of decision to move from /people & /organisation to /profile/firstname-lastname and profile/organisation-title.

**Comment by finnlewis** [comment]
https://github.com/IIED-org/pubs/pull/322 should fix this @cbrody
