### ISSUE TITLE
field_collection rename to field_collections

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#146]
Coming from https://github.com/IIED-org/pubs/pull/144

We need to rename field_collection to field_collections to avoid config and schema confusion.

**Comment by cbrody** [comment]
@finnlewis The value for field_short_description appears not to be carried across in the Collection taxonomy migration. E.g:
http://pubs-dev.ac.iied.org/taxonomy/term/40525/edit
The value for the Short description field should be "How IIED supports just transitions towards locally-controlled forestry that safeguard biocultural heritage, enhance entrepreneurship and improve prosperity within diverse and resilient landscapes" as per:
https://www.iied.org/taxonomy/term/2341/edit

**Comment by finnlewis** [comment]
Hi @cbrody 

This should be fixed with https://github.com/IIED-org/pubs/pull/159

Note: I ran into an interesting error on migration: 

```
 [error]  Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_short_description_value' at row 1: INSERT INTO "taxonomy_term__field_short_description" ("entity_id", "revision_id", "bundle", "delta", "langcode", "field_short_description_value") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5); Array
(
    [:db_insert_placeholder_0] => 41059
    [:db_insert_placeholder_1] => 41239
    [:db_insert_placeholder_2] => collection
    [:db_insert_placeholder_3] => 0
    [:db_insert_placeholder_4] => und
    [:db_insert_placeholder_5] => How IIED engages with local groups, regional associations and national federations of locally-controlled forestry organisations to upscale effective climate change adaptation, resilience and mitigation through the restoration of forest landscape biodiversity
)
 in Drupal\Core\Entity\Sql\SqlContentEntityStorage->saveToDedicatedTables() (line 1383 of /app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
```

Turns out the source field allows up to 400 characters, the destination on 255, which is sensible for short plain text fields and I think the default in Drupal 9.

I've trimmed thr source value down to 255 characters, which means we will be losing a little from the short description of taxonomy/term/3161 - https://www.iied.org/localising-forest-climate-action

Is that OK or do we need to consider changing the destination field?

**Comment by cbrody** [comment]
@ncktrnr Do you have a view on Finn's comment (above)?

**Comment by ncktrnr** [comment]
Yes, that seems fine to me. It should indeed be a short description.

**Comment by cbrody** [comment]
@finnlewis Fine to truncate any rogue 'short' titles to 255 chars, thanks.

**Comment by finnlewis** [comment]
Hey @cbrody - great, should be fine to merge https://github.com/IIED-org/pubs/pull/159 - shall I leave that to you?

**Comment by cbrody** [comment]
Merged and closed, thanks!
