### ISSUE TITLE
Image styles used within rich text fields.

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#173]
Coming from discussion on #99 about images in the body.

@cbrody would like to explore re-writing the image tags within rich-text fields to remove the reference to legacy image styles and re-write the paths to the original source file or perhaps a preferred default image style.

For example, 

```
<img alt="Map of the EPIC project sites in Burkina Faso. Click on the image to expand. (Image: Sylvain Zabré and Fabiola Monty/IUCN)" class="caption image-max540" height="382" src="/sites/default/files/styles/max540/public/2018-12-19_ebaburkinafasomap.png?itok=yVSs1h3x" title="Map of the EPIC project sites in Burkina Faso. Click on the image to expand. (Image: Sylvain Zabré and Fabiola Monty/IUCN)" width="540" /> 
```

So, for each migration that includes rich text sources, we need to scan for all legacy image style patterns.

@ncktrnr could you suggest a default image style that would be appropriate.

**Comment by ncktrnr** [comment]
Some of original image files are quite large, so I think a default image style would be best. I added a style to the current site based on Tailwind max-width called 'max-w-3xl’ which scales images to 768px. Not ideal, but at least images will only scale down, not up. Sorry for delayed response.

**Comment by finnlewis** [comment]
Hi @ncktrnr and @cbrody ! I imported the config from the latest dev-master branch but I don't seem to have an image style that matches 'max-w-3xl'. Is it on another branch and if so can we merge it back to dev-master?

Many thanks,

Finn

**Comment by ncktrnr** [comment]
Sorry! There should be a style on dev-master branch called 'scale-md’ which does the same (scale width 768px). I’d intended to update the name to max-w-3xl to match the Tailwind class, but doesn’t really matter. Hope that’s OK to use instead?

**Comment by finnlewis** [comment]
Discussing with @cbrody - this articel has multiple images in and is a good test case: 

https://www.iied.org/conservation-discrimination-case-studies-nepals-national-parks

**Comment by cbrody** [comment]
D7 image audit: https://www.iied.org/admin/image-audit

**Comment by finnlewis** [comment]
This piece of work is revealing files that do not appear to be in the fiels_managed table and therefore have not been migrated:


From https://www.iied.org/best-2018-blogs 

- https://www.iied.org/sites/default/files/styles/100x100/public/pictures/picture-717-1365766523.jpg

From https://www.iied.org/iieds-best-2019-blogs (node 24276)
 - "pictures/picture-66-1334666115.jpg" 
 - https://www.iied.org/sites/default/files/styles/100x100/public/pictures/picture-66-1334666115.jpg

From https://www.iied.org/iieds-best-2021-blogs
 - "pictures/picture-46-1632907681.jpg" from node 139931
 - https://www.iied.org/sites/default/files/styles/180x180/public/pictures/picture-46-1632907681.jpg?itok=uY8ulLy6

Taking a look at the migrated nodes in Drupal 9, it reveals other images that are also missing.

Not sure how best to deal with these missing images that are not managed by Drupal.
