### ISSUE TITLE
Migrate: Rewrite image paths from FQDN to relative paths

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#205]
Coming from https://github.com/IIED-org/pubs/issues/173#issuecomment-1115949752

On https://www.iied.org/iieds-best-2019-blogs 
It turns out we have image paths with the full domain name in the path: 

https://www.iied.org/sites/default/files/styles/100x100/public/pictures/picture-66-1334666115.jpg

So we probably need to rewrite these to relative paths.

**Comment by finnlewis** [comment]
This also raises other questions about existing paths and domains.....

For example: 

- https://pubs.iied.org/13616iied
- /pubs/display.php?o=G02319
- http://www.iied.org/pubs/display.php?o=14531IIED
- https://www.iied.org/users/liz-carlile

**Comment by cbrody** [comment]
@mattjobob also need your input on this.

**Comment by cbrody** [comment]
Details in https://docs.google.com/spreadsheets/d/1NTbnHFZDLOkhvxlUUdvVSaplt0rKx97v1XXr_j2GSkA/edit#gid=0

@DavidIIED your input would be useful, particularly on pubs URLs.

**Comment by cbrody** [comment]
See also #223

**Comment by cbrody** [comment]
Images not managed by Drupall will need to be manually migrated. scale_md images were not being generated, fixed in #311.

**Comment by cbrody** [comment]
@finnlewis I discovered another image path pattern that needs a rewrite:
`src="/files/filename.ext" > src="sites/default/files/filename.ext"`
See row 14 here: https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=0

**Comment by finnlewis** [comment]
https://github.com/IIED-org/pubs/pull/321 should fix this @cbrody - please review!

**Comment by cbrody** [comment]
Thanks @finnlewis - merged but please see https://github.com/IIED-org/pubs/pull/321#issuecomment-1192145127
