### ISSUE TITLE
Build: add and configure default_content

### ISSUE THREAD

**Issue by cbrody** [IIED-org/pubs#209]
For global taxonomy terms, footer menu, sample pages (see content to create spreadsheet) 
using default_content_deploy and default_content modules

Sample pages are listed in bold on the 'content to create' spreadsheet.

- [x] Install and enable modules
- [x] Configure 
- [x] Add global taxonomy terms
- [x] Main menu
- [ ] Footer menu
- [ ] Default taxonomy pages
- [ ] Sample long read

**Comment by cbrody** [comment]
Module added and enabled, needs setting up.

**Comment by cbrody** [comment]
Testing locally

**Comment by cbrody** [comment]
@ncktrnr After adding them locally I've exported the Main menu and Global taxonomy terms to the default content directory, and imported them successfully to [Acquia dev](https://pubs-dev.ac.iied.org). I can talk you through the process of adding more content when we meet next.

**Comment by ncktrnr** [comment]
Great, let's talk through the process next week. In the meantime I've created a list of menus, terms and sample nodes we can add. See Content to create or recreate spreadsheet for details.
