### ISSUE TITLE
Build: upgrade media_ pdf_thumbnail module

### ISSUE THREAD

**Issue by cbrody** [IIED-org/pubs#246]
Installed version no longer supported

- [x] Freeze production site and copy db & files to stage/local dev
- [x] `lando drush cim`
- [x] Uninstall existing version `lando drush pm-uninstall media_pdf_thumbnail; lando drush cr`
- [x] Update code `lando composer require drupal/media_pdf_thumbnail:^5.0`
- [x] `lando drush en -y media_pdf_thumbnail`
- [x] Update field formatters in affected media/document view modes
- [x] Export config
- [x] Deploy to stage & test
- [x] Deploy to production
- [x] Implement on dev-master
- [x] Update relevant twig templates

**Comment by cbrody** [comment]
.lando file now include fix-imagick command which needs to be run for image generation to work locally:
`lando fix-imagick
lando restart`

**Comment by cbrody** [comment]
Investigate, find a way forward

**Comment by cbrody** [comment]
@ncktrnr the various publication card templates need to be updated following this upgrade.

**Comment by cbrody** [comment]
On theme pages e.g. https://pubs-dev.ac.iied.org/communication publications slider cards with replacement cover images (e.g https://pubs-dev.ac.iied.org/g04143) aren't displayed in a consistent format.

**Comment by cbrody** [comment]
@ncktrnr can this be closed?

**Comment by ncktrnr** [comment]
> @ncktrnr can this be closed?

Yes, fine to close
