### ISSUE TITLE
Gin toolbar not showing

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/pubs#276]
![Image](https://user-images.githubusercontent.com/15605937/173179966-9d4aa82b-d6cb-4dc0-894c-76a354c64830.png)

Layout builder gin module extends the admin theme for layout pages. Looks good, but the toolbar with save button isn't showing correctly. See screenshot
https://www.drupal.org/project/gin_lb

**Comment by cbrody** [comment]
Adding the following fixes the issue temporarily, but still a mystery as to why this should be necessary.
```
.glb-toolbar {
    opacity: 1;
    top: 0;
  }
```
