### ISSUE TITLE
Review how best to use this repo and current hosting environment

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#96]
This repo is the live Drupal 9 https://pubs.iied.org/

We'll be using this as the starting point for the future Drupal 9 unifified site. 

We'll need to confisder how best to manage branches, dev / stage / live hosting environments while we're building and migrating.

**Comment by finnlewis** [comment]
Hi @cbrody 

I cloned your forked repo https://github.com/cbrody/IIEDnew , which is actually a fork of this one.

I don't have commit access to https://github.com/cbrody/IIEDnew but I do have commit access to this one.

Shall we use this repo for the Drupal 9 upgrade and migration work, or create another repo in the https://github.com/IIED-org organisation to use going forward? If we use this one, I'm sure we could rename it in the future as it wil be more than just 'pubs'. 

Cheers,

Finn

**Comment by cbrody** [comment]
Hi @finnlewis as discussed let's use this repo going forward, with the dev-master branch as the main one for merging new features into and for testing on Acquia dev. We'll continue to use the master branch for security updates and hotfixes. At some point (when?) it would make sense to rename the repo to match the lando site name ( #97 ) 

Cheers,
Chris
