### ISSUE TITLE
Lando: local developer setup 

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#97]
Extend lando file to support dev migration work. 

Add documentation for developer setup.

**Comment by finnlewis** [comment]
Hi @cbrody 

Just wondering about the name for the local Lando site.

It is currently gwi.lndo.site. 

Why is it called gwi? 

Would something like iied-org.lndo.site be better? 

Or iied-main.lndo.site?

Many thanks,

Finn

**Comment by finnlewis** [comment]
Hi @cbrody 
Just wondering if you might like to try the Lando setup on this branch: https://github.com/IIED-org/pubs/tree/feature/lando-updates
Might need to `lando destroy` and  `lando start` again to make sure everything is fresh.

**Comment by cbrody** [comment]
Thanks @finnlewis for your work on this. Shall we use IIED-main as the name for the unified site going forward?

**Comment by finnlewis** [comment]
Good call @cbrody 

Lando file now refers to iied-main: https://github.com/IIED-org/pubs/blob/feature/97-lando-updates/.lando.yml#L1
