### ISSUE TITLE
Migrate content: project nodes

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#99]
This issue is to track the initial migration of project nodes from the Drupal 7 https://www.iied.org/ site to the new Drupal 9 site. 

Initial tasks (may evolve): 

- [x] Stub out IIED D7 migration module
- [x] #100
- [x] Create migration from source Project nodes into destination project nodes
- [x] Build out updated project content type in the Drupal 9 site
- [x] Extend migration to map all fields.

**Comment by cbrody** [comment]
No individual projects have been identified as good test cases - it probably doesn't matter which are chosen

For the time being we'll assume that pubs.iied.org/productCode URLs will map to www.iied.org/productCode in the unified site. In the Project content type the Publications field is not required (these will be displayed via entity ref) and the Additional resources field can be left as is for now.

**Comment by finnlewis** [comment]
Hi @cbrody 

This branch is ready for some testing. 
Would you like to get is set up locally to test the migrations, or would you like me to demo it to you on a video call or both?
I've added some migration specific documentation to the README in https://github.com/IIED-org/pubs/tree/feature/99-migrate-content-projects/docroot/modules/custom/iied_migrate_d7 
Let me know what the best route to testing ahead of a merge request is.

Many thanks,

Finn

**Comment by cbrody** [comment]
Thanks Finn. 

I've got a local D7 database imported into the IIED-main app's d7db, with files copied from production as documented in the module's README. I attempted to run the full iied_d7_migrate group, but this failed as follows:

```
[notice] Processed 19517 items (0 created, 0 updated, 19517 failed, 0 ignored) - done with 'iied_d7_files'

In MigrateToolsCommands.php line 978:

  iied_d7_files Migration - 19517 failed.
```

My next steps will be to re-import the D9 database from Pubs production, run config import again and attempt a single migration of the D7 files, examining any resulting error messages.

n.b. there was an minor issue relating to field.storage.node.field_work_programme_global_enga.yml which caused an error on the D9 config import (I've now checked out the relevant file from master) - there are likely to be other merge conflicts, which we can deal with as they arise.

I'll raise a ticket with Acquia support on the issue of connecting to the D7 (iiedorg) database and file system from the Pubs/irforum application's dev environment.

**Comment by cbrody** [comment]
Just to clarify, does the file migration move the files to a new location, or just reference the original source?

**Comment by cbrody** [comment]
Does this migration need to be run as with the --update flag for it to work correctly? The process seems to empty some existing fields e.g. ProjectNumber (legacy), Year and (IIED) NID.

**Comment by finnlewis** [comment]
Just to answer your last comment on here, @cbrody, I think this is now covered. 
We specify the overwrite_properties key which means that when a node is already present, only those fields that we list will be overwritten: 

https://github.com/IIED-org/pubs/blob/dev-master/docroot/modules/custom/iied_migrate_d7/config/install/migrate_plus.migration.iied_d7_projects.yml#L209-L240

For discussion, see: 

https://www.drupal.org/project/drupal/issues/2949564

**Comment by cbrody** [comment]
@finnlewis as discussed the Blogger info field seems to contain a copy of the body field instead of field_blogger_info content.

**Comment by cbrody** [comment]
@finnlewis Projects are missing field_collections entity reference values e.g. 
http://pubs-dev.ac.iied.org/align-advancing-land-based-investment-governance
Missing the Collection value of [Legal tools for citizen empowerment](https://www.iied.org/legal-tools-for-citizen-empowerment). Source node:
https://www.iied.org/node/28371/edit

**Comment by cbrody** [comment]
It looks like project nodes that have been updated via #123, which doesn't change the entity's modified date, may be missing updated info in some fields. Needs further testing.

**Comment by finnlewis** [comment]
From our conversation today, the body field updates might not be being pulled through where we've updated links. I will test this with a fresh migration from scratch.

@cbrody if you do have specific node IDs to check, that would be fab!

**Comment by cbrody** [comment]
@finnlewis this one has images in the body field:
https://www.iied.org/node/19291

**Comment by finnlewis** [comment]
Hi @cbrody 

Testing a fresh migration, I think the issue with the missing images in the body field is actually to do with image styles. 

One image tag in the body field is as follows: 

```
<img alt="Map of the EPIC project sites in Burkina Faso. Click on the image to expand. (Image: Sylvain Zabré and Fabiola Monty/IUCN)" class="caption image-max540" height="382" src="/sites/default/files/styles/max540/public/2018-12-19_ebaburkinafasomap.png?itok=yVSs1h3x" title="Map of the EPIC project sites in Burkina Faso. Click on the image to expand. (Image: Sylvain Zabré and Fabiola Monty/IUCN)" width="540" /> 
```
This was originally using the 'max540' image style on the Drupal 7 site. We don't have that style on the Drupal 9 site. Probably best to recreate legacy image styles to catch these images embedded in the body.

I will continute testing the project migration, as it is the odd one out insofar as we are updated previously migrated content and want to make sure it is catching all the data and taxonomy terms but not overwriting legacy fields.

**Comment by finnlewis** [comment]
Hi @cbrody, 

I've fixed the field_collections issue by adding the field to the "overwrite_properties" key in the migration definition which I clearly missed first time around, sorry. This is particular to the "iied_d7_projects" migration, as we already have the project nodes migrated in from the RSS feed and so are updating specific fields on exisitng nodes. 

We should double check that all fields we want to be overwritten by our update migration are listed here. https://github.com/IIED-org/pubs/blob/cc179387696e87706da5a7aecd2d682c62b2e2d1/docroot/modules/custom/iied_migrate_d7/config/install/migrate_plus.migration.iied_d7_projects.yml#L209-L241

As far as I can see all fields are listed there, but it would be worth a second pair of eyes in case I've missed something else!

Many thanks,

Finn

**Comment by finnlewis** [comment]
See https://github.com/IIED-org/pubs/pull/172

**Comment by cbrody** [comment]
> Probably best to recreate legacy image styles to catch these images embedded in the body.

Not sure as this would mean creating a lot of legacy styles that we don't really want to be using anyway. Perhaps an alternative would be to rewrite such paths with an appropriate image style that does exist. Let's discuss this afternoon.

**Comment by cbrody** [comment]
A few outstanding issues with images, please see [Testing spreadsheet](https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=635051503) for details.

**Comment by finnlewis** [comment]
From the [Testing spreadsheet](https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=635051503) it looks like there are two issues.


### 19291

- D7 NID: 	19291	
- D7 URL: https://www.iied.org/eba-evidence-policy-burkina-faso	
- Testing URL: https://pubs-dev.ac.iied.org/eba-evidence-policy-burkina-faso	
- Path: /eba-evidence-policy-burkina-faso	
- Problemo: body field missing styled image

Assessment:
I have the styled image on my local at https://iied-main.lndo.site/sites/default/files/styles/scale_md/public/images/2019/01/09/2018-12-19_ebaburkinafasomap.png?itok=yVSs1h3x, so it seems unlikely to be a problem directly with the migrations.
On the testing site, we can reach the original image here: https://pubs-dev.ac.iied.org/sites/default/files/images/2019/01/09/2018-12-19_ebaburkinafasomap.png?itok=yVSs1h3x

So for some reason the scale_md image style is not being generated. I can't seem to log it to check the logs, but it would be good to a) confirm the image style is present and b) see what logs Drupal or PHP is generating.

**Comment by finnlewis** [comment]
### 6395

- D7 NID: 6395
- D7 URL: https://www.iied.org/ghana-our-way-participatory-reform-artisanal-small-scale-mining-sector
- Testing URL: https://pubs-dev.ac.iied.org/ghana-our-way-participatory-reform-artisanal-small-scale-mining-sector
- Path: /ghana-our-way-participatory-reform-artisanal-small-scale-mining-sector
- Problemo: body field missing styled image

#### Assessment

I think we're talking about the ASM_countries_map_3.jpg image. 
In which case, I can't see the image on the D7 site: 
https://www.iied.org/files/styles/float_right/public/images/2017/01/19/ASM_countries_map_3.jpg?itok=r4_oke7d

Looking at the path, it is missing sites/default in the image file path.

Indeed, adding that shows me the image on the D7 site:
https://www.iied.org/sites/default/files/styles/float_right/public/images/2017/01/19/ASM_countries_map_3.jpg?itok=r4_oke7d

Again, looks like the original image is here: https://pubs-dev.ac.iied.org/sites/default/files/ASM_countries_map_3.jpg?itok=r4_oke7d 
But the image style is either not present or does not work: https://pubs-dev.ac.iied.org/sites/default/files/styles/float_right/public/ASM_countries_map_3.jpg?itok=r4_oke7d

**Comment by cbrody** [comment]
Thanks @finnlewis I'm happy to close this as the issues are not related to the migration process.
